### ISSUE TITLE
gcr.io/cloud-builders-community/ng - BUILD FAILURE

### ISSUE THREAD

**Issue by rpbaquing-cloudmade** [GoogleCloudPlatform/cloud-builders-community#566]
## Affected builder image

gcr.io/cloud-builders-community/ng

## Expected Behavior

create all the images when submitted to cloud build.

## Actual Behavior

```
Step #0: Step 3/4 : RUN npm install -g @angular/cli@$ng_version --unsafe-perms &&     ng version
Step #0:  ---> Running in a5c0c518ca51
Step #0: npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
Step #0: npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
Step #0: npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
Step #0: npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
Step #0: npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
Step #0: npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
Step #0: npm WARN deprecated cryptiles@2.0.5: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
Step #0: npm WARN deprecated sntp@1.0.9: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
Step #0: npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
Step #0: npm WARN deprecated boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
Step #0: npm WARN deprecated har-validator@5.1.5: this library is no longer supported
Step #0: npm WARN deprecated hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
Step #0: npm WARN deprecated har-validator@4.2.1: this library is no longer supported
Step #0: npm WARN deprecated browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
Step #0: npm WARN deprecated har-validator@5.1.5: this library is no longer supported
Step #0: npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
Step #0: npm WARN deprecated hawk@3.1.3: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
Step #0: npm WARN deprecated request@2.81.0: request has been deprecated, see https://github.com/request/request/issues/3142
Step #0: npm WARN deprecated chokidar@1.7.0: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
Step #0: npm WARN deprecated extract-text-webpack-plugin@3.0.2: Deprecated. Please use https://github.com/webpack-contrib/mini-css-extract-plugin
Step #0: npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
Step #0: npm WARN deprecated uglify-es@3.3.9: support for ECMAScript is superseded by `uglify-js` as of v3.13.0
Step #0: npm WARN deprecated html-webpack-plugin@2.30.1: out of support
Step #0: npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
Step #0: npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
Step #0: npm WARN deprecated core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
Step #0: npm notice 
Step #0: npm notice New patch version of npm available! 8.5.2 -> 8.5.5
Step #0: npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.5.5>
Step #0: npm notice Run `npm install -g npm@8.5.5` to update!
Step #0: npm notice 
Step #0: npm ERR! code 1
Step #0: npm ERR! path /usr/local/lib/node_modules/@angular/cli/node_modules/node-sass
Step #0: npm ERR! command failed
Step #0: npm ERR! command sh -c node scripts/build.js
Step #0: npm ERR! Building: /usr/local/bin/node /usr/local/lib/node_modules/@angular/cli/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
Step #0: npm ERR! gyp info it worked if it ends with ok
Step #0: npm ERR! gyp verb cli [
Step #0: npm ERR! gyp verb cli   '/usr/local/bin/node',
Step #0: npm ERR! gyp verb cli   '/usr/local/lib/node_modules/@angular/cli/node_modules/node-gyp/bin/node-gyp.js',
Step #0: npm ERR! gyp verb cli   'rebuild',
Step #0: npm ERR! gyp verb cli   '--verbose',
Step #0: npm ERR! gyp verb cli   '--libsass_ext=',
Step #0: npm ERR! gyp verb cli   '--libsass_cflags=',
Step #0: npm ERR! gyp verb cli   '--libsass_ldflags=',
Step #0: npm ERR! gyp verb cli   '--libsass_library='
Step #0: npm ERR! gyp verb cli ]
Step #0: npm ERR! gyp info using node-gyp@3.8.0
Step #0: npm ERR! gyp info using node@17.7.2 | linux | x64
Step #0: npm ERR! gyp verb command rebuild []
Step #0: npm ERR! gyp verb command clean []
Step #0: npm ERR! gyp verb clean removing "build" directory
Step #0: npm ERR! gyp verb command configure []
Step #0: npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
Step #0: npm ERR! gyp verb `which` failed Error: not found: python2
Step #0: npm ERR! gyp verb `which` failed     at getNotFoundError (/usr/local/lib/node_modules/@angular/cli/node_modules/which/which.js:13:12)
Step #0: npm ERR! gyp verb `which` failed     at F (/usr/local/lib/node_modules/@angular/cli/node_modules/which/which.js:68:19)
Step #0: npm ERR! gyp verb `which` failed     at E (/usr/local/lib/node_modules/@angular/cli/node_modules/which/which.js:80:29)
Step #0: npm ERR! gyp verb `which` failed     at /usr/local/lib/node_modules/@angular/cli/node_modules/which/which.js:89:16
Step #0: npm ERR! gyp verb `which` failed     at /usr/local/lib/node_modules/@angular/cli/node_modules/isexe/index.js:42:5
Step #0: npm ERR! gyp verb `which` failed     at /usr/local/lib/node_modules/@angular/cli/node_modules/isexe/mode.js:8:5
Step #0: npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21)
Step #0: npm ERR! gyp verb `which` failed  python2 Error: not found: python2
Step #0: npm ERR! gyp verb `which` failed     at getNotFoundError (/usr/local/lib/node_modules/@angular/cli/node_modules/which/which.js:13:12)
Step #0: npm ERR! gyp verb `which` failed     at F (/usr/local/lib/node_modules/@angular/cli/node_modules/which/which.js:68:19)
Step #0: npm ERR! gyp verb `which` failed     at E (/usr/local/lib/node_modules/@angular/cli/node_modules/which/which.js:80:29)
Step #0: npm ERR! gyp verb `which` failed     at /usr/local/lib/node_modules/@angular/cli/node_modules/which/which.js:89:16
Step #0: npm ERR! gyp verb `which` failed     at /usr/local/lib/node_modules/@angular/cli/node_modules/isexe/index.js:42:5
Step #0: npm ERR! gyp verb `which` failed     at /usr/local/lib/node_modules/@angular/cli/node_modules/isexe/mode.js:8:5
Step #0: npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21) {
Step #0: npm ERR! gyp verb `which` failed   code: 'ENOENT'
Step #0: npm ERR! gyp verb `which` failed }
Step #0: npm ERR! gyp verb check python checking for Python executable "python" in the PATH
Step #0: npm ERR! gyp verb `which` failed Error: not found: python
Step #0: npm ERR! gyp verb `which` failed     at getNotFoundError (/usr/local/lib/node_modules/@angular/cli/node_modules/which/which.js:13:12)
Step #0: npm ERR! gyp verb `which` failed     at F (/usr/local/lib/node_modules/@angular/cli/node_modules/which/which.js:68:19)
Step #0: npm ERR! gyp verb `which` failed     at E (/usr/local/lib/node_modules/@angular/cli/node_modules/which/which.js:80:29)
Step #0: npm ERR! gyp verb `which` failed     at /usr/local/lib/node_modules/@angular/cli/node_modules/which/which.js:89:16
Step #0: npm ERR! gyp verb `which` failed     at /usr/local/lib/node_modules/@angular/cli/node_modules/isexe/index.js:42:5
Step #0: npm ERR! gyp verb `which` failed     at /usr/local/lib/node_modules/@angular/cli/node_modules/isexe/mode.js:8:5
Step #0: npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21)
Step #0: npm ERR! gyp verb `which` failed  python Error: not found: python
Step #0: npm ERR! gyp verb `which` failed     at getNotFoundError (/usr/local/lib/node_modules/@angular/cli/node_modules/which/which.js:13:12)
Step #0: npm ERR! gyp verb `which` failed     at F (/usr/local/lib/node_modules/@angular/cli/node_modules/which/which.js:68:19)
Step #0: npm ERR! gyp verb `which` failed     at E (/usr/local/lib/node_modules/@angular/cli/node_modules/which/which.js:80:29)
Step #0: npm ERR! gyp verb `which` failed     at /usr/local/lib/node_modules/@angular/cli/node_modules/which/which.js:89:16
Step #0: npm ERR! gyp verb `which` failed     at /usr/local/lib/node_modules/@angular/cli/node_modules/isexe/index.js:42:5
Step #0: npm ERR! gyp verb `which` failed     at /usr/local/lib/node_modules/@angular/cli/node_modules/isexe/mode.js:8:5
Step #0: npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21) {
Step #0: npm ERR! gyp verb `which` failed   code: 'ENOENT'
Step #0: npm ERR! gyp verb `which` failed }
Step #0: npm ERR! gyp ERR! configure error 
Step #0: npm ERR! gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
Step #0: npm ERR! gyp ERR! stack     at PythonFinder.failNoPython (/usr/local/lib/node_modules/@angular/cli/node_modules/node-gyp/lib/configure.js:484:19)
Step #0: npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/@angular/cli/node_modules/node-gyp/lib/configure.js:406:16)
Step #0: npm ERR! gyp ERR! stack     at F (/usr/local/lib/node_modules/@angular/cli/node_modules/which/which.js:68:16)
Step #0: npm ERR! gyp ERR! stack     at E (/usr/local/lib/node_modules/@angular/cli/node_modules/which/which.js:80:29)
Step #0: npm ERR! gyp ERR! stack     at /usr/local/lib/node_modules/@angular/cli/node_modules/which/which.js:89:16
Step #0: npm ERR! gyp ERR! stack     at /usr/local/lib/node_modules/@angular/cli/node_modules/isexe/index.js:42:5
Step #0: npm ERR! gyp ERR! stack     at /usr/local/lib/node_modules/@angular/cli/node_modules/isexe/mode.js:8:5
Step #0: npm ERR! gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:198:21)
Step #0: npm ERR! gyp ERR! System Linux 5.10.0-11-cloud-amd64
Step #0: npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/@angular/cli/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
Step #0: npm ERR! gyp ERR! cwd /usr/local/lib/node_modules/@angular/cli/node_modules/node-sass
Step #0: npm ERR! gyp ERR! node -v v17.7.2
Step #0: npm ERR! gyp ERR! node-gyp -v v3.8.0
Step #0: npm ERR! gyp ERR! not ok 
Step #0: npm ERR! Build failed with error code: 1
Step #0: 
Step #0: npm ERR! A complete log of this run can be found in:
Step #0: npm ERR!     /root/.npm/_logs/2022-03-19T08_00_43_827Z-debug-0.log
Step #0: The command '/bin/sh -c npm install -g @angular/cli@$ng_version --unsafe-perms &&     ng version' returned a non-zero code: 1
Finished Step #0
ERROR
ERROR: build step 0 "gcr.io/cloud-builders/docker" failed: step exited with non-zero status: 1
Step #0: 
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

BUILD FAILURE: Build step failure: build step 0 "gcr.io/cloud-builders/docker" failed: step exited with non-zero status: 1
ERROR: (gcloud.builds.submit) build 94c67d5a-f723-43dd-bdd2-0c70c3c07e41 completed with status "FAILURE"
```

## Steps to Reproduce the Problem

1. Clone the cloud-builders-community repo:
```
$ git clone https://github.com/GoogleCloudPlatform/cloud-builders-community
```
2. Go to the directory that has the source code for the packer Docker image:
```
$ cd cloud-builders-community/packer
```
3. Build the Docker image:
```
$ gcloud builds submit --config cloudbuild.yaml .
```

**Comment by DavideBonfanti** [comment]
I've just made a [PR](https://github.com/GoogleCloudPlatform/cloud-builders-community/pull/567) for this

**Comment by rpbaquing-cloudmade** [comment]
Thanks @DavideBonfanti, yeah my reproduce steps is incorrect. It should be ng. Anyway, the build is successful now. Thank you for the fix!
